# Generated by Django 5.1.1 on 2024-11-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='times_borrowed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
