# Generated by Django 5.1.1 on 2024-11-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0002_alter_inventoryitem_times_borrowed'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechaccounts',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
