# Generated by Django 5.1.1 on 2024-11-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0006_remove_cart_email_borrowing_records_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccounts',
            name='verification',
            field=models.CharField(default='Not Activated', max_length=50),
        ),
    ]
