# Generated by Django 5.1.1 on 2024-11-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0007_alter_studentaccounts_verification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentaccounts',
            old_name='verification',
            new_name='status',
        ),
        migrations.AddField(
            model_name='staff_faculty_accounts',
            name='status',
            field=models.CharField(default='Activated', max_length=50),
        ),
    ]
