# Generated by Django 5.1.1 on 2024-11-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0009_alter_studentaccounts_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentaccounts',
            name='status',
            field=models.CharField(default='Not Activated', max_length=50),
        ),
    ]
