# Generated by Django 5.1.1 on 2024-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0010_alter_studentaccounts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowing_records',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
