# Generated by Django 5.1.1 on 2024-11-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0011_borrowing_records_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_records',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
