# Generated by Django 5.1.1 on 2024-11-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0012_alter_borrowing_records_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_records',
            name='items_borrowed',
            field=models.CharField(max_length=255),
        ),
    ]
