# Generated by Django 5.1.1 on 2024-12-17 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0015_studentaccounts_confirmation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccounts',
            name='confirmation_token',
        ),
    ]
