# Generated by Django 5.1.1 on 2024-12-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0016_remove_studentaccounts_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccounts',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
