# Generated by Django 5.1.1 on 2024-12-27 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0018_studentaccounts_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccounts',
            name='last_login',
        ),
    ]
