# Generated by Django 5.1.1 on 2024-12-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0019_remove_studentaccounts_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentaccounts',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentaccounts',
            name='verification_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
