# Generated by Django 5.1.1 on 2024-12-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0020_studentaccounts_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentaccounts',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='studentaccounts',
            name='status',
            field=models.CharField(default='Not Verified', max_length=50),
        ),
    ]
