# Generated by Django 5.1.1 on 2025-01-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TUPCLaboratoryEquipment', '0022_archived_equipments_date_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing_records',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Handed In', 'Handed In'), ('Returned', 'Returned'), ('Overdue', 'Overdue'), ('Void', 'Void')], default='Pending', max_length=10),
        ),
    ]
